- name: install a mysql deb package from the internet.
  apt:
    deb: https://dev.mysql.com/get/mysql-apt-config_0.8.13-1_all.deb
  become: yes
  tags: mysql

- name: install mysql
  apt:
    name: mysql-server
    state: present
    update_cache: yes
  become: yes
  tags: mysql

- name: 
  lineinfile:
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    line: "bind-address = 0.0.0.0"
  become: yes
  tags: mysql

- name: 
  lineinfile:
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    line: "default-authentication-plugin = mysql_native_password"
  become: yes
  tags: mysql

- name: deamon reload
  systemd:
    name: mysql.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: yes
  tags: mysql

- name: get root password
  shell: "grep 'A temporary password is generated for root@localhost' /var/log/mysqld.log | awk -F ' ' '{print $(NF)}'"
  register: root_password
  become: yes
  tags: mysql

- name: upload my.cnf
  template:
    src: my-before.cnf.j2
    dest: /etc/my-before.cnf
    owner: root
    group: root
    mode: 0755
  become: yes
  tags: mysql

- name: upload my.cnf
  template:
    src: my-after.cnf.j2
    dest: /etc/my-after.cnf
    owner: root
    group: root
    mode: 0755
  become: yes
  tags: mysql

- name: upload mysql.sh
  template:
    src: mysql.sh.j2
    dest: /root/mysql.sh
    owner: root
    group: root
    mode: 0777
  become: yes
  tags: mysql

- name: Run script
  command: sh /root/mysql.sh
  become: yes
  tags: mysql

- name: remove my.cnf
  file:
    path: /etc/my-before.cnf
    state: absent
  become: yes
  tags: mysql

- name: remove my.cnf
  file:
    path: /etc/my-after.cnf
    state: absent
  become: yes
  tags: mysql

- name: remove mysql.sh
  file:
    path: /root/mysql.sh
    state: absent
  become: yes
  tags: mysql
