- name: install aptitude
  apt: 
    pkg: 
      - python-apt
      - aptitude
  become: yes
  tags: common

- name: apt update && apt upgrade -y
  apt:
    upgrade: dist
    update_cache: yes
  become: yes
  tags: common

- name: install some packages
  apt:
    name:
      - git
      - build-essential
      - curl
      - zsh
      - vim
      - unzip
      - dstat
      - siege
      - tree
      - percona-toolkit
    state: present
    update_cache: yes
  become: yes
  tags: common

- name: change hostname
  hostname:
    name: "{{ inventory_hostname }}"
  become: yes
  tags: common

- name: copy env.sh
  copy:
    src: env.sh
    dest: /etc/profile.d/env.sh
    owner: root
    group: root
    mode: 0755
  become: yes
  tags: common

- name: enable sudo path
  replace:
    dest: /etc/sudoers
    regexp: '^Defaults	env_reset'
    replace: '#Defaults	env_reset'
  become: yes
  tags: common

- name: enable sudo path
  replace:
    dest: /etc/sudoers
    regexp: '^Defaults	secure_path'
    replace: '#Defaults	secure_path'
  become: yes
  tags: common