- name: install aptitude
  apt: 
    pkg: 
      - python-apt
      - aptitude
  become: yes
  tags: common

- name: apt update && apt upgrade -y
  apt:
    upgrade: dist
    update_cache: yes
  become: yes
  tags: common

- name: install some packages
  apt:
    name:
      - git
      - build-essential
      - curl
      - zsh
      - gawk
      - vim
      - unzip
      - dstat
      - siege
      - tree
      - htop
      - percona-toolkit
    state: present
    update_cache: yes
  become: yes
  tags: common

- name: change hostname
  hostname:
    name: "{{ inventory_hostname }}"
  become: yes
  tags: common

- name: copy env.sh
  copy:
    src: env.sh
    dest: /etc/profile.d/env.sh
    owner: root
    group: root
    mode: 0755
  become: yes
  tags: common

- name: download .zshrc
  get_url:
    url: https://gist.github.com/AkashiSN/4ff2eb541742bedb3d281725b6d15c3f/raw/zshrc
    dest: /home/isucon/.zshrc
    mode: '0440'
  tags: common

- name: get the username running the deploy
  command: whoami
  register: username

- name: change to zsh
  user:
    name: isucon
    shell: /bin/zsh
  become: yes
  tags: common

- name: enable sudo path
  replace:
    dest: /etc/sudoers
    regexp: '^Defaults	env_reset'
    replace: '#Defaults	env_reset'
  become: yes
  tags: common

- name: enable sudo path
  replace:
    dest: /etc/sudoers
    regexp: '^Defaults	secure_path'
    replace: '#Defaults	secure_path'
  become: yes
  tags: common