- name: check test
  stat:
    path: /usr/local/rbenv
  register: result
  become: yes
  tags: ruby

- name: install dependency rbenv
  apt:
    name:
      - libreadline-dev
      - zlib1g-dev
      - libssl-dev
      - libmysqlclient-dev
    state: present
    update_cache: yes
  become: yes
  tags: ruby

- name: install rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: /usr/local/rbenv
  when: result.stat.exists == false
  become: yes
  tags: ruby

- name: copy rbenv.sh
  copy:
    src: rbenv.sh
    dest: /etc/profile.d/rbenv.sh
    owner: root
    group: root
    mode: 0755
  when: result.stat.exists == false
  become: yes
  tags: ruby

- name: install ruby-build
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: /usr/local/rbenv/plugins/ruby-build
  when: result.stat.exists == false
  become: yes
  tags: ruby

- name: change owner group rbenv directory
  file:
    path: /usr/local/rbenv
    owner: root
    group: root
    recurse: yes
    state: directory
  when: result.stat.exists == false
  become: yes
  tags: ruby

- name: install ruby
  shell: bash -lc "rbenv install 2.6.4"
  when: result.stat.exists == false
  become: yes
  tags: ruby

- name: set global
  shell: bash -lc "rbenv global 2.6.4"
  when: result.stat.exists == false
  become: yes
  tags: ruby

- name: install bundler
  gem:
    name: bundler
    user_install: no
    executable: /usr/local/rbenv/shims/gem
  when: result.stat.exists == false
  become: yes
  tags: ruby

- name: add /etc/profile.d
  lineinfile:
    dest: /home/isucon/.zshrc
    line: "source /etc/profile.d/rbenv.sh"
  when: result.stat.exists == false
  become: yes
  tags: ruby
